<?php // lang_es.php
$lang = array(
    'title' => 'Welcome',
    'description' => 'L.O.V.E.',
    'home' => 'Home',
    'about' => 'About Us',
    'pages' => 'Pages',
    'causes' => 'Causes',
    'blog' => 'Blog',
    'contact' => 'Contact',
    'collection' => 'Collection',
    'friends' => 'Friends of the Center',
    'subscription' => 'Subscription',
    'website_name' => 'Justo & Catherine González Resource Center',
    'about_the' => 'About the González Center',
    'mission' => 'Our Mission',
    'mission_statement' => 'To promote and support the Latino contribution to the formation of ministerial leaders through dialogue, educational resources and research.',
    'more_about' => 'More About Us',
    'support_hispanic' => 'Suport Hispanic Community',
    'goal'=>'Our Goal',
    'goal_1' => 'A meeting place both physical and virtual that:',
    'goal_2' => 'Raises awareness of Latino perspectives and Latino heritage by providing digital access to its resources;',
    'goal_3' => 'Explores new frontiers in Latin theology, and provides a forum for people committed to the well-being of Latino churches and communities to explore and develop new visions and practices.',
    'vision' => 'Our Vision',
    'vision1' => 'A meeting place both physical and virtual that:',
    'vision2' => 'Raises awareness of Latino perspectives and Latino heritage by providing digital access to its resources;',
    'vision3' => 'Explores new frontiers in Latin theology, and provides a forum for people committed to the well-being of Latino churches and communities to explore and develop new visions and practices.',
    'testimonial1' => 'The writings of Justo and Catherine González have helped Christians around the world understand church history in new and deeper ways. The Resource Center does essential work in making these materials available to all people',
    'testimonial2' => 'Justo González life work is a treasure, and I am thrilled to know that it will be made so widely available for posterity through the Justo and Catherine González Resource Center',
    'testimonial3' => 'The breadth of their work in history, theology, and ministerial formation makes the González Resource Center an indispensable site of archival research and dynamic conversation about many of the most pressing theological questions of our time',
    'testimonial4' => 'By embracing their legacy, we foster a more inclusive, ecumenical, and vibrant theological landscape, where bridges are built between academia, seminaries, and the broader Church community',
    'testimonial5' => 'When I look back upon the last century of theological education and pastoral leadership in the United States and across the world, I can think of no two people as influential as Justo and Catherine González. ',
    'email_address' => 'Email Address',
    'our_location' => 'Our location',
<<<<<<< HEAD
    'fell_free' => 'Feel Free to Contact with us',
    'justo_influence' => 'Dr. Justo L. Gonzálezs influence in Hispanic theology is profound, as he has been a pivotal figure in elevating the voices and perspectives of Hispanic Christians in theological discourse. Through his writings and teachings, he has addressed issues of cultural identity, social justice, and the relevance of biblical texts to the experiences of Latina/o communities. His work has encouraged a deeper understanding of the intersection between faith and culture, fostering a more inclusive theological landscape that honors the rich diversity within Christianity. By mentoring young theologians, González continues to inspire the next generation to explore and articulate their own theological insights, further enriching the field of Hispanic theology.',
    'justo_legacy' => 'González Legacy',
    'justo_legacy_1' => 'Dr. Justo L. González is a distinguished theologian, historian, and educator, particularly known for his contributions to Hispanic theology. Born and raised in Havana, Cuba, González was ordained as a minister in the Methodist church in 1957. He later earned his Ph.D. in Historical Theology from Yale University in 1961, becoming the youngest person to do so at the time',
    'justo_legacy_2' => 'Over his career, González has taught at various theological institutions, including the Seminario Evangélico de Puerto Rico and the Candler School of Theology at Emory University. He has authored more than 150 books, with notable works such as "A History of Christian Thought" and "The Story of Christianity," which have been translated into multiple languages.',
    'justo_legacy_3' => 'Dr. González has been instrumental in promoting Hispanic theological education. He helped found the Hispanic Theological Initiative, the Hispanic Summer Program, and the Asociación para la Educación Teológica Hispana (AETH). His commitment to education is further reflected in the Justo and Catherine González Resource Center, established in 2011 to support Latino/a ministries',
    'justo_legacy_4' => 'Even after retiring from full-time teaching, González continues to write, lecture, and mentor young theologians. He has received numerous accolades, including four honorary doctorates and the Distinguished Service Medal from the Association of Theological Schools.',
    'justo_legacy_5' => 'González`s work has significantly shaped Latina/o biblical hermeneutics and constructive theology, advocating for the recognition of theology`s contextual nature and its enrichment through diverse cultural perspectives',
    'degrees' => array(
        'bachelor_of_arts' => '<strong>Bachelor of Arts (B.A.):</strong> He earned his undergraduate degree in theology from the University of Havana in Cuba.',
        'bachelor_of_divinity' => '<strong>Bachelor of Divinity (B.D.):</strong> González obtained his B.D. from the Union Theological Seminary in New York.',
        'phd_historical_theology' => '<strong>Ph.D. in Historical Theology:</strong> He earned his Ph.D. from Yale University in 1970, becoming the youngest person to do so at that time.',
        'doctor_of_ministry' => '<strong>Doctor of Ministry (D.Min.):</strong> He also holds a Doctor of Ministry degree, which emphasizes practical application of theology in ministry contexts.',
        'honorary_doctorates' => '<strong>Honorary Doctorates:</strong> Dr. González has received multiple honorary doctorates from various institutions in recognition of his contributions to theology and education, although the specific institutions and degrees vary.',
    ),
    'achievements' => array(
        'first_latino_phd' => '<strong>First Latino to Earn a Ph.D. from Yale University:</strong> Dr. González became the youngest person and the first Latino to graduate with a Ph.D. in Historical Theology from Yale in 1970.',
        'ordained_minister' => '<strong>Ordained Minister:</strong> He was ordained as a minister in the Methodist Church in 1957, beginning his long commitment to ministry and theological education.',
        'prolific_author' => '<strong>Prolific Author:</strong> Dr. González has authored over 150 books on theology, history, and ministry, significantly contributing to the fields of Hispanic and Latina/o theology.',
        'advocate_hispanic_education' => '<strong>Advocate for Hispanic Theological Education:</strong> He has been instrumental in promoting and developing theological education for Hispanic communities, helping establish programs that cater to their unique cultural contexts.',
        'educator_renowned_institutions' => '<strong>Educator at Renowned Institutions:</strong> Dr. González has taught at various prestigious theological institutions, including the Candler School of Theology at Emory University and the Interdenominational Theological Center in Atlanta.',
        'international_speaker' => '<strong>International Speaker and Lecturer:</strong> Dr. González has lectured widely across the globe, sharing his insights on Hispanic theology, church history, and the intersection of faith and culture.',
        'member_american_academy' => '<strong>Member of the American Academy of Arts and Sciences:</strong> His scholarly contributions have earned him a place in this prestigious organization, recognizing his influence in the humanities.',
        'founder_hispanic_initiative' => '<strong>Founder of The Hispanic Theological Initiative:</strong> He co-founded this initiative to enhance the training and support of Hispanic scholars in theological education.',
    ),


    '' => '',
=======
    '' => '',
   
>>>>>>> f7d7ad2 (web)
);
