<?php // lang_pt.php
$lang = array(
    'title' => 'Bem-vindo',
    'description' => 'L.O.V.E.',
    'home' => 'Início',
    'about' => 'Sobre Nós',
    'pages' => 'Páginas',
    'causes' => 'Causas',
    'blog' => 'Blog',
    'contact' => 'Contato',
    'collection' => 'Coleção',
    'friends' => 'Amigos do Centro',
    'subscription' => 'Assinatura',
    'website_name' => 'Centro de Recursos Justo & Catherine Gonzalez',
    'about_the' => 'Sobre o Centro Gonzalez',
    'mission' => 'Nossa Missão',
    'mission_statement' => 'Promover e apoiar a contribuição Latino para a liderança ministerial através de diálogo, recursos educacionais e pesquisa.',
    'more_about' => 'Mais Sobre Nós',
    'support_hispanic' => 'Apoie a Comunidade Hispânica',
    'goal' => 'Nosso Objetivo',
    'goal_1' => 'Um lugar físico e virtual que:',
    'goal_2' => 'Aumenta a conscientização sobre perspectivas e herança latino-americanas, proporcionando acesso digital aos seus recursos;',
    'goal_3' => 'Explora novas fronteiras na teologia latino-americana e oferece um fórum para aqueles comprometidos com o bem-estar das igrejas e comunidades latinas para Coleçãoexplorar e desenvolver novas visões e práticas.',
    'vision' => 'Nossa Visão',
    'vision1' => 'Um lugar físico e virtual que:',
    'vision2' => 'Aumenta a conscientização sobre perspectivas e herança latino-americanas, proporcionando acesso digital aos seus recursos;',
    'vision3' => 'Explora novas fronteiras na teologia latino-americana e oferece um fórum para aqueles comprometidos com o bem-estar das igrejas e comunidades latinas para explorar e desenvolver novas visões e práticas.',
    'testimonial1' => 'Os escritos de Justo e Catherine Gonzalez ajudaram cristãos ao redor do mundo a entender a história da igreja de novas e mais profundas maneiras. O Centro de Recursos está realizando um trabalho essencial ao tornar esses materiais disponíveis para todos.',
    'testimonial2' => 'O trabalho de Justo Gonzalez é um tesouro, e estou empolgado em saber que será amplamente disponível para a posteridade através do Centro de Recursos Justo e Catherine Gonzalez.',
    'testimonial3' => 'A amplitude de seu trabalho em história, teologia e formação ministerial torna o Centro de Recursos Gonzalez um local indispensável para pesquisa arquivística e conversa dinâmica sobre muitas das questões teológicas mais urgentes de nosso tempo.',
    'testimonial4' => 'Ao abraçar seu legado, fomentamos um cenário teológico mais inclusivo, ecumênico e vibrante, onde pontes são construídas entre a academia, seminários e a comunidade eclesiástica mais ampla.',
    'testimonial5' => 'Quando olho para o último século de educação teológica e liderança pastoral nos Estados Unidos e ao redor do mundo, não consigo pensar em duas pessoas mais influentes do que Justo e Catherine Gonzalez.',
    'testimonial6' => 'Através do Centro Justo e Catherine Gonzalez, eles continuarão a inspirar, desafiar e encorajar as futuras gerações a abraçar, apreciar e celebrar o contínuo trabalho da graça abundante de Deus.',
    'email_address' => 'Endereço de E-mail',
    'our_location' => 'Nossa Localização',
    'fell_free' => 'Sinta-se à vontade para nos contatar',
    'justo_influence' => 'A influência do Dr. Justo L. Gonzalez na teologia hispânica é profunda, pois ele tem sido uma figura chave na elevação das vozes e perspectivas dos cristãos hispânicos no discurso teológico. Através de seus escritos e ensinamentos, ele abordou questões de identidade cultural, justiça social e a relevância dos textos bíblicos nas experiências das comunidades latinas. Seu trabalho promove uma compreensão mais profunda da interseção entre fé e cultura, promovendo um cenário teológico mais inclusivo que honra a rica diversidade dentro do cristianismo. Ao orientar jovens teólogos, Gonzalez continua a inspirar a próxima geração a explorar e articular suas próprias percepções teológicas, enriquecendo ainda mais o campo da teologia hispânica.',
    'justo_legacy' => 'Legado de González',
    'justo_legacy_1' => 'Justo Luis González nasceu em Havana, Cuba, em agosto de 1937. Durante sua juventude, seus pais lançaram as bases para uma carreira que já dura mais de 60 anos. Sua mãe, Luisa García Acosta, era educadora, professora de literatura espanhola e autora de diversos livros sobre gramática. Seu pai, Justo González Carrasco, era romancista, editor de um jornal e funcionário do Ministério da Agricultura de Cuba, onde principalmente pegava materiais escritos por cientistas sobre temas como agricultura, higiene e plantas medicinais, e os reescrevia de maneira que aqueles sem educação formal ampla pudessem entender e aplicar o que liam. Justo pai frequentemente dizia que quem não conseguia explicar algo em termos simples provavelmente não o entendia.',
    'justo_legacy_2' => 'Justo aprendeu essa lição diretamente com seu pai, quando orgulhosamente lhe apresentou uma redação que havia sido muito elogiada pela professora. Após lê-la repetidamente, seu pai perguntou: "O que você quis dizer?" Quando Justo explicou, a resposta de seu pai foi: "Então, por que você não disse isso?"',
    'justo_legacy_3' => 'Essa lição é visível em tudo o que Justo escreve, frequentemente pegando conceitos difíceis e explicando-os de uma maneira que qualquer pessoa interessada possa entender, independentemente do nível de educação formal que possua. Isso é claramente visto em seus mais de 150 livros, entre eles <i>História do Cristianismo e História do Pensamento Cristão</i>, traduzidos para dez idiomas.',
    'justo_legacy_4' => 'Após completar seus estudos teológicos no Seminário Evangélico de Teologia em Matanzas, Cuba, em 1957, ser ordenado ministro metodista no mesmo ano, e concluir seu doutorado (PhD) em teologia histórica na Universidade de Yale – aos 23 anos de idade – ele foi para Porto Rico, onde ensinou história da igreja no Seminário Evangélico de Porto Rico por oito anos. De lá, passou a lecionar na escola de teologia Candler, na Universidade de Emory. Por mais de 45 anos, Justo tem focado sua atenção no desenvolvimento de programas para a educação teológica do povo hispânico. Isso resultou, entre outras coisas, no Programa Hispano de Verão (HSP), na Associação para a Educação Teológica Hispânica (AETH) e na Iniciativa Teológica Hispânica (HTI). A importância de seu trabalho foi reconhecida com inúmeros prêmios e distinções, entre eles sete doutorados honoris causa, o "Lifetime Achievement Award" da Associação de Escolas Teológicas (ATS) e, acima de tudo, um público leitor de alcance global.',
    'justo_legacy_5' => 'Após sua "aposentadoria", Justo continua escrevendo, dando palestras e inspirando novas gerações de líderes para a igreja, particularmente entre o povo hispânico.',
    'justo_legacy_6' => 'Ele é casado com a Reverenda Dra. Catherine Gunsalus González, com quem colabora tanto em palestras quanto em escritos conjuntos. Eles têm uma filha, duas netas e três bisnetos.',


    'video' => 'Vídeos Gonzalez',
    'gallery' => 'Galeria',
    'Advanced_Search' => 'Busca Avançada',
    'Faceted_Search' => 'Busca Facetada',
    'User_Friendly_Interface' => 'Interface Amigável',
    'Rich_Metadata_Integration' => 'Integração de Metadados Ricos',
    'discovery' => 'Descubra o Magnífico Acervo',
    'discovery_description1' => 'Nossa plataforma orgulha-se de exibir o magnífico conteúdo do acervo de Justo e Catherine Gonzalez, oferecendo uma riqueza incomparável de informações e recursos para pesquisa e exploração aprofundadas. Esta coleção exclusiva é um verdadeiro tesouro de insights valiosos e dados históricos, meticulosamente curada para o pesquisador exigente.',
    'discovery2' => 'Desbloqueie o Acesso Premium',
    'discovery_description2' => 'Para manter os mais altos padrões de privacidade e integridade, o acesso a este conteúdo extraordinário está disponível através de um login seguro. Não perca a oportunidade de mergulhar nesta coleção excepcional—entre em contato conosco para obter suas credenciais de acesso e explorar a riqueza do nosso acervo.',
    'youtube_title' => 'Bem-vindo ao Canal de Vídeos Gonzalez',
    'youtube_description' => 'Mergulhe no mundo exclusivo de Justo e Catherine Gonzalez com nosso canal do YouTube, sua porta de entrada para uma rica coleção de conteúdos selecionados. Nosso canal oferece uma variedade de vídeos únicos e insights que não estão disponíveis em outros lugares.',
    'Exclusive_Content' => 'Conteúdo Exclusivo',
    'youtube_description2' => 'Desfrute de acesso a uma gama de vídeos exclusivos, incluindo explorações detalhadas, entrevistas e conteúdo de bastidores relacionado a Justo e Catherine Gonzalez. Descubra materiais raros e exclusivos que fornecem uma compreensão mais profunda de seu trabalho e legado.',
    'friend_of_the_center_title' => 'Torne-se um Amigo do Centro',
    'friend_of_the_center_description' => 'Junte-se a nós para sustentar o valioso trabalho do Centro de Recursos Justo Gonzalez tornando-se um “Amigo do Centro.” Seu apoio é crucial para manter e aprimorar os recursos e programas do nosso centro.',
    'Friends' => 'Amigos',
    'why_become' => 'Por Que Se Tornar um Amigo do Centro?',
    'sustain_services' => '<strong>Sustente Serviços Essenciais:</strong> Sua doação mensal ou anual ajuda a garantir que nosso centro continue a fornecer serviços e recursos essenciais para aqueles que precisam.',
    'preserve_resources' => '<strong>Preserve Recursos Valiosos:</strong> As contribuições nos ajudam a manter e expandir nossa coleção, permitindo-nos oferecer mais materiais e oportunidades valiosas para pesquisa e educação.',
    'make_impact' => '<strong>Faça um Impacto Duradouro:</strong> Ao se juntar ao programa “Amigo do Centro”, você desempenha um papel vital na preservação e promoção do legado de Justo Gonzalez, garantindo que as futuras gerações possam continuar a acessar e aprender com este recurso inestimável.',
    'benefits' => 'Benefícios de Participar',
    'exclusive_updates' => '<stronAtualizações Exclusivas: Receba atualizações regulares sobre as atividades do centro, novas aquisições e eventos especiais.',
    'recognition' => 'Reconhecimento: Como um sinal de nossa gratidão, você será reconhecido por seu apoio generoso em nossas publicações e em nosso site.',
    'special_access' => 'Acesso Especial: Desfrute de acesso exclusivo a eventos especiais e prévias de novos recursos e coleções.',
    'how_to_get_involved' => 'Como Se Envolver',
    'simple_process' => 'Tornar-se um “Amigo do Centro” é simples. Escolha um plano de doação mensal ou anual que se encaixe no seu orçamento e faça a diferença na sustentabilidade do Centro de Recursos Justo Gonzalez.',
    'support_mission' => 'Apoie nossa missão, preserve nosso patrimônio e faça parte de algo significativo. Junte-se a nós hoje e ajude-nos a continuar nosso trabalho importante!',
    'join_us' => 'Junte-se a Nós',
    'catherine_gonzalez_profile' => 'Catherine Gunsalus González nasceu em 20 de maio de 1934, em uma família com profundas raízes na história dos Estados Unidos. A casa na fazenda no interior do estado de Nova York, que pertence à família há várias gerações — e onde a mãe de Catherine nasceu — foi uma das estações do “trem subterrâneo” que ajudava escravos afro-americanos a escapar para o Canadá. Sua família se mudou para os arredores de Nova York em 1943, mas continuavam passando os verões naquela fazenda, lugar que guarda boas memórias para Catherine. Ela foi educada nas escolas públicas de Nova York e depois frequentou o Beaver College (hoje Arcadia University), onde se formou em história e ciências políticas, após ter abandonado seus estudos anteriores em economia doméstica. Depois, frequentou a Universidade de Boston, onde cursou tanto o seminário quanto o doutorado em teologia. Após se formar em 1965, lecionou no West Virginia Wesleyan College, e naquele mesmo ano foi ordenada como Ministra da Palavra e do Sacramento pela Igreja Presbiteriana Unida. Em 1970, começou a lecionar no Seminário Teológico Presbiteriano de Louisville, onde foi a primeira mulher professora. Quando se juntou ao corpo docente do Seminário Teológico de Columbia, em janeiro de 1974, também foi a primeira mulher a fazer parte da equipe docente. Essa mudança de seminários ocorreu devido ao seu casamento com Justo L. González, que na época era professor na Universidade de Emory, a três milhas de Columbia. Catherine abriu caminho para várias outras mulheres que a seguiram. Ela se aposentou em 2002, recebendo o título de Professora Emérita do Seminário Teológico de Columbia, onde continuou a ministrar cursos por vários anos.',
    'catherine_gonzalez_contributions' => 'Seu casamento com Justo foi uma verdadeira educação. Catherine, que nunca havia estado na América Latina, começou sua rápida imersão em questões de educação teológica hispânica durante sua lua de mel — que foi combinada com as repetidas conferências de Justo em diversos lugares e com a busca de oportunidades para promover a educação teológica latina. Especialmente nas décadas de 80 e 90, eles ministravam palestras conjuntas, nas quais combinavam o estudo bíblico com preocupações sobre questões de equidade de gênero e raça. Isso reflete como compartilharam interesses e se apoiaram mutuamente durante seus mais de 50 anos de casamento.',
    'catherine_gonzalez_impact' => 'Quando chegou sua “aposentadoria”, suas viagens constantes aumentaram, assim como o interesse de Catherine tanto nas igrejas latinas de longa data nos Estados Unidos quanto nas igrejas de imigrantes, que cresciam continuamente.',
    'catherine_gonzalez_impact2' => 'Após a pandemia, as dificuldades de mobilidade limitaram suas viagens, mas Catherine ainda continua suas atividades teológicas e históricas, encontrando tempo para suas paixões por culinária e nutrição, além de ler romances de mistério e acompanhar fielmente o time de beisebol Atlanta Braves.',

    'gonzalez_center_description' => array(
        'legacy_title' => '<strong>Criando um Legado de Excelência Teológica</strong>',
        'legacy_description' => 'O Centro de Recursos Justo e Catherine Gonzalez se destaca como um farol de excelência no estudo teológico latino, forjando um legado profundo no campo da fé e da exploração intelectual. Nomeado em homenagem a Justo e Catherine Gonzalez, o Centro incorpora seu compromisso com o avanço da compreensão teológica e a promoção de um ambiente acadêmico rico para estudiosos e praticantes latinos.',
        'majesty_title' => '<strong>Um Majestoso Repositório de Conhecimento</strong>',
        'majesty_description' => 'No coração do Centro Gonzalez está seu majestoso repositório de recursos, cuidadosamente curado para apoiar e aprimorar o estudo da teologia latina. A extensa coleção do Centro abrange uma ampla gama de temas, incluindo teologia histórica, teologia da libertação e estudos culturais, refletindo a profundidade e diversidade do pensamento latino. Ao fornecer acesso a uma vasta gama de materiais acadêmicos, o Centro permite que pesquisadores, estudantes e teólogos explorem e se envolvam com as perspectivas sutis que moldam as tradições cristãs latinas.',
        'contribution_title' => '<strong>Contribuindo para a Teologia Latina Hoje</strong>',
        'contribution_description' => 'O Centro Gonzalez desempenha um papel fundamental na formação da teologia latina hoje, servindo como um centro central para pesquisa e educação teológica. Através de seus robustos programas e recursos, o Centro promove o desenvolvimento de novas ideias teológicas e incentiva a exploração de questões críticas dentro das comunidades latinas. Suas iniciativas incluem:
            <ul>
                <li><strong>Preservação e Promoção do Patrimônio Teológico Latino:</strong> O Centro protege o rico patrimônio teológico do cristianismo latino, garantindo que obras e contribuições significativas sejam preservadas e acessíveis para as gerações futuras.</li>
                <li><strong>Suporte a Pesquisadores Emergentes:</strong> Ao oferecer suporte à pesquisa, mentoria e oportunidades de desenvolvimento profissional, o Centro fomenta a próxima geração de teólogos e estudiosos latinos, capacitando-os a fazer contribuições significativas no campo.</li>
                <li><strong>Promoção do Diálogo Acadêmico:</strong> O Centro organiza conferências, palestras e workshops que reúnem estudiosos, praticantes e líderes comunitários para participar de diálogos sobre questões teológicas e sociais urgentes, promovendo uma comunidade acadêmica vibrante e colaborativa.</li>
                <li><strong>Ampliação do Acesso Educacional:</strong> Através de seus recursos digitais e programas educacionais, o Centro expande o acesso à educação teológica, possibilitando que um público mais amplo se envolva com o pensamento e a erudição teológica latina.</li>
            </ul>',
    ),

    'gonzalez_center_faq' => array(
        'question_1' => '<strong>O que é o Centro de Recursos Justo e Catherine Gonzalez?</strong>',
        'answer_1' => 'O Centro de Recursos Justo e Catherine Gonzalez é uma instituição dedicada a preservar e promover o legado teológico e acadêmico de Justo e Catherine Gonzalez. Ele fornece acesso a uma vasta coleção de recursos, incluindo livros, artigos e materiais relacionados à teologia hispânica.',

        'question_2' => '<strong>Como posso acessar os recursos do Centro?</strong>',
        'answer_2' => 'Os recursos estão disponíveis online através do nosso site. Para acesso completo a alguns materiais, pode ser necessário credenciais específicas, que podem ser solicitadas entrando em contato com o centro.',

        'question_3' => '<strong>Qual é a missão do Centro de Recursos?</strong>',
        'answer_3' => 'Nossa missão é promover e apoiar a contribuição latina para a formação de líderes ministeriais por meio de diálogo, recursos educacionais e pesquisa, ajudando a expandir a compreensão da teologia hispânica.',

        'question_4' => '<strong>Como posso me tornar um "Amigo do Centro"?</strong>',
        'answer_4' => 'Você pode se tornar um "Amigo do Centro" fazendo uma doação mensal ou anual. Os detalhes para se inscrever e contribuir estão disponíveis na nossa página de "Amigos do Centro" no site.',

        'question_5' => '<strong>Quais são os benefícios de se tornar um "Amigo do Centro"?</strong>',
        'answer_5' => 'Como "Amigo do Centro", você receberá atualizações exclusivas, reconhecimento em nossas publicações e site, e acesso especial a eventos e novos recursos.',

        'question_6' => '<strong>O Centro organiza eventos ou palestras?</strong>',
        'answer_6' => 'Sim, o Centro organiza eventos, palestras e webinars sobre tópicos relevantes para a teologia hispânica e o legado de Justo e Catherine Gonzalez. As datas e detalhes são atualizados regularmente em nosso site.',

        'question_7' => '<strong>Onde posso encontrar os materiais e livros de Justo e Catherine Gonzalez?</strong>',
        'answer_7' => 'Os materiais e livros estão disponíveis em nossa biblioteca online. Para acessar obras específicas, utilize nossa plataforma de pesquisa e catálogos digitais.',

        'question_8' => '<strong>Como posso fazer uma doação ao Centro?</strong>',
        'answer_8' => 'As doações podem ser feitas através do nosso site, onde você encontrará opções para contribuições únicas, mensais ou anuais. As doações ajudam a manter e expandir nossos recursos e programas.',
    ),
    'ceo_description' => array(
        'title' => 'Ondina Gonzalez - Diretora',
        'description' => '<p>Ondina E. González é natural de Cuba, de onde emigrou para os Estados Unidos com sua família quando tinha menos de três anos de idade. Um ano depois, sua família se estabeleceu na cidade de Rome, na Geórgia, onde os pais de Ondina trabalharam no Berry College até sua aposentadoria na década de 90.</p><p>O pai de Ondina, Jorge A. González, era especialista em Antigo Testamento; e sua mãe, Ondina S. González, era muito ativa entre as mulheres metodistas unidas, tanto em nível local quanto nacional. Portanto, não é surpreendente que, em seu lar, houvesse tanto interesse pelo serviço quanto pela educação, e que essas duas paixões tenham guiado a vida de Ondina.</p><p>Após receber simultaneamente um bacharelado em história e um mestrado em história colonial da América Latina, Ondina obteve outro título avançado em finanças internacionais pela American Graduate School of International Management, em Phoenix, Arizona. Retornando à história, ela obteve seu Ph.D. pela Universidade de Emory em 2001.</p><p>Desde então, Ondina lecionou em várias instituições – entre elas, Agnes Scott College e a Universidade de Emory. Mais recentemente, tem se dedicado a servir como Diretora do Centro de Recursos Justo e Catherine González, colaborando neste programa que faz parte da Associação para a Educação Teológica Hispana.</p>',

    ),
    'getaccessdatabase' => 'Acesse agora nossa Coleção Digital!',
    'clickhere' => 'Clique aqui',
    'database_desc1' => '<b>Desbloqueie um mundo de conhecimento e recursos</b> com acesso exclusivo à nossa coleção digital! Se você está pesquisando, aprendendo ou explorando, nossos recursos digitais curados estão aqui para apoiar sua jornada.',
    'database_desc2' => 'Benefícios do Acesso:',
    'database_desc3' => '<b>Arquivos Extensos:</b> Explore uma vasta gama de documentos, publicações e recursos multimídia.',
    'database_desc4' => '<b>Informação Atualizada:</b> Mantenha-se informado com as últimas atualizações e adições à nossa coleção.',
    'database_desc5' => '<b>Interface Amigável:</b> Navegue e pesquise facilmente os materiais que você precisa.',
    'database_desc6' => '<b>Não perca este recurso valioso!</b> Inscreva-se ou Faça login para começar a explorar nossa coleção digital hoje mesmo.',
    'welcome_description' => array(
        'p1' => 'Bem-vindo',
        'p2' => 'Estamos muito felizes que você tenha reservado um tempo para nos visitar.',
        'p3' => 'Aqui você encontrará uma abundância de recursos para apoiá-lo em seu ministério, seus estudos e em sua jornada pessoal de fé.',
        'p4' => 'Talvez o nosso recurso mais acessível seja a coleção digital das obras inéditas do Dr. Justo L. González e daquelas que ele fez com a Dra. Catherine G. González. Esta coleção é um exemplo tangível do importante legado que esses dois grandes líderes da igreja criaram ao longo de mais de 60 anos dedicados à vida da igreja e à educação de seus líderes. Até agora, no entanto, carregamos apenas uma parte dos centenas de documentos mantidos pelo Centro.',
        'p5' => 'Navegue neste site e saiba mais sobre o trabalho que estamos realizando. Leia sobre o Centro como um lugar de encontro, um espaço para sonhar com as inúmeras maneiras pelas quais latinos e latinas podem contribuir para a igreja universal e um lugar onde a história do impacto dos cristãos hispânicos é celebrada e honrada. Saiba sobre o início do Centro como parte da AETH. Conheça aqueles de nós que orientam o trabalho do Centro González e saiba como você também pode apoiar esse trabalho.',
        'p6' => 'O acesso a esses recursos maravilhosos mantidos em nossa coleção é por meio de assinatura, que pode ser adquirida através da AETH ou tornando-se Amigo do Centro (veja abaixo). Role mais para baixo e você encontrará um exemplo de um dos documentos já carregados em nossa coleção.',
        'p7' => 'Este estudo bíblico, publicado em El Discípulo, é um de uma série de treze que abrange um trimestre inteiro de domingos. Já temos várias dessas séries carregadas e disponíveis para aqueles que têm acesso à coleção, e continuaremos a carregar mais no futuro.',
        'p8' => 'Para mais exemplos de alguns de nossos recursos, por favor, visite a página de Coleções neste site <a href="%s">clicando aqui.</a>',
        'p9' => 'Para apoiar este importante legado e o trabalho do Centro criado em nome de Justo e Catherine, estabelecemos o programa Amigos do Centro. Este programa é uma via para aqueles que acreditam na necessidade de continuar e expandir o acesso ao trabalho dos González, não apenas através da coleção digital, mas também através das várias outras maneiras pelas quais o Centro apoia e nutre o trabalho dos líderes ministeriais em toda a igreja.',
        'p10' => '<a href="%s">Clique aqui</a> para saber mais sobre o programa e as muitas maneiras pelas quais confiamos nos Amigos para orientar nosso trabalho.',
        'p11' => 'Se você preferir fazer uma doação única em vez de um compromisso contínuo com o nosso trabalho, por favor, <a href="https://aeth.info/_donacion-justo-center" target="_blank"> clique aqui</a> para ser redirecionado. Saiba que, de qualquer forma que você escolher se tornar parte do importante trabalho que estamos realizando, agradecemos muito sua contribuição e humildemente pedimos suas orações.',
    ),

    'director' => 'Diretora',
    'junior' => array(
        'p1' => 'Wilson Fernandes Junior',
        'p2' => '<p>Conhecido por muitos simplesmente como Junior, brasileiro e compartilha uma jornada de 26 anos com sua esposa, Keyla. Juntos, têm criado seus dois filhos, Daniel (23) e Vitor (21), no norte da Geórgia desde 2018.</p><p>Desenvolvedor full stack por profissão, com um pós-graduação em Análise e Desenvolvimento de Sistemas pela USP no Rio de Janeiro, Brasil, e um diploma em Administração de Sistemas, Junior é dedicado à criação de soluções digitais que atendem às necessidades do mundo dinâmico de hoje. No entanto, seu trabalho vai além do campo da tecnologia; seu propósito mais profundo é servir ao Senhor Jesus Cristo.</p><p>A paixão de Junior pela música se expressa através de seu papel como tecladista e líder de adoração na Igreja Brazil House em Johns Creek, GA. Nessa função, ele lidera outros em adoração, ajudando-os a se tornarem uma parte integral do corpo de Cristo e a seguir a Sua vontade.</p><p>Sua jornada de fé começou aos 12 anos, e desde então, ele tem se dedicado a espalhar a mensagem de amor e esperança. Seus esforços contribuíram para o estabelecimento de igrejas tanto no Brasil quanto nos Estados Unidos.</p><p>Além de seus papéis profissionais e ministeriais, Junior desempenha um papel vital no Centro Justo, onde tem sido fundamental no desenvolvimento de ferramentas e processos para digitalizar os vastos arquivos do centro.</p>',
    ),
    'sophia' => array(
        'p1' => 'Sophia Porter',
        'p2' => '<p>Sophia Porter é estagiária no Centro de Recursos Justo e Catherine González, onde trabalha com o programa Amigo/as do Centro. Ela é estudante atual do curso de Mestrado em Divindade na Candler School of Theology e mora em Atlanta, Geórgia.</p><p> Ela nasceu e foi criada em Marion, Indiana, onde também fez sua graduação. Ela se formou na Indiana Wesleyan University com especializações em Desenvolvimento Comunitário e Ministérios Pastorais.</p><p>Após a graduação, ela estudou linguística espanhola e história na Universidad de Nebrija em Madrid, Espanha.</p><p>Aparte dos estudos, ela adora passar tempo com sua família e amigos próximos. Ela tem aproveitado bastante seu tempo no Centro e espera continuar o trabalho que está sendo realizado.</p>'
    ),
    'jessica' => array(
        'p1' => 'Dr. Jessica Lugo',
        'p2' => '<p>A Revda. Dra. Jessica Lugo Meléndez nasceu em San Juan, PR e cresceu em Deltona, Flórida. Ela é uma ministra ordenada das Igrejas Batista Americanas e faz parte do corpo pastoral das Igrejas Batista de Porto Rico. Ela é professora de História do Cristianismo, Novo Testamento e Evangelismo.</p><p>Com mais de 20 anos de experiência ministerial e secular combinada, a Dra. Lugo escreveu para várias referências teológicas, eclesiásticas e administrativas. Ela possui Doutorado em Ministério pela Liberty University e um MDiv pelo Seminário Evangélico de Porto Rico.</p><p>Em 2024, a Dra. Lugo se tornou a nona Diretora Executiva da Associação para a Educação Teológica Hispana (AETH), supervisionando seus mais de cinco programas, incluindo o Centro de Recursos Justo e Catherine González. Sob sua liderança, a AETH ampliou seus esforços para apoiar e fortalecer a educação teológica para hispânicos.</p>'
    ),
    'donate' => 'Donar Ahora',
    'ourCollection' => 'Nossa Coleção',
    'friends_desc' => array(
        'p1' => 'Se você deseja se envolver mais com o valioso trabalho realizado no Centro de Recursos Justo e Catherine González, considere se tornar um Amigo do Centro. Nossos Amigos são colaboradores vitais para manter e melhorar nossos recursos e programas. Esta parceria é inestimável para nosso trabalho e ajuda a garantir que os recursos do Centro continuem acessíveis ao maior número possível de pessoas.',
        'p2' => 'Os Amigos do Centro são pessoas que apoiam o trabalho e a visão do Centro tanto financeiramente quanto com seus comentários, sugestões e contribuições.',
        'p3' => '<b>Contribuições e sugestões.</b> Como membro deste grupo, suas contribuições e sugestões não só são bem-vindas, mas também solicitadas. Para que seus comentários sejam significativos, você receberá atualizações periódicas sobre as atividades do Centro, bem como acesso à coleção digital do Centro, que geralmente está disponível apenas por assinatura, enquanto permanecer um Amigo. Ao ler sobre o que estamos fazendo ou ao examinar as coleções digitais, esperamos que você nos diga de que forma poderíamos melhorar, quais recursos deveríamos oferecer e nos informe sobre erros que devem ser corrigidos. (Para saber mais sobre a coleção digital, clique aqui.)',
        'p4' => '<b>Comunicação.</b> Como parte do programa Amigos, também enviaremos peças mensais para reflexão. Esses breves ensaios são escritos por pessoas que, como você, estão em uma jornada de fé, já trabalharam ou ainda trabalham em algum tipo de ministério e nos convidam a refletir mais profundamente sobre vários aspectos da fé. Alguns ensaios estarão relacionados ao calendário cristão; no tempo comum, as reflexões geralmente focam em como e onde podemos experimentar Deus de forma mais próxima. Ocasionalmente, recorremos às palavras de pessoas que nos precederam, como Isidoro de Sevilha, para ler pensamentos que inspiraram muitos ao longo dos anos.',
        'p5' => '<b>Apoio financeiro.</b> Indivíduos que fazem uma doação anual de $200,00 ou mais para o Centro terão automaticamente uma assinatura de um ano ao programa de Amigos. Aqueles que fizerem doações mensais recorrentes de $15 ou mais serão Amigos enquanto a contribuição continuar. Se você deseja se tornar um Amigo do Centro, por favor, entre em contato com Luz Ortiz por e-mail em lzortiz@aeth.org ou por telefone no 407-773-1234.',
        'p6' => 'Seu apoio nos ajudará a manter e expandir nossa coleção e nos permitirá oferecer mais materiais valiosos para pesquisa e educação. Portanto, considere fazer um impacto duradouro ao ingressar no programa Amigos do Centro. Você desempenha um papel vital na preservação e promoção do legado de Justo e Catherine González, garantindo que as futuras gerações possam continuar acessando e aprendendo com esses recursos inestimáveis.',
    ),

    'acervo_desc' => array(
        'p1' => 'Você já se perguntou como acessar o trabalho de um dos maiores líderes cristãos contemporâneos da comunidade latina, um de seus mais importantes historiadores e um dos seus mais bem-sucedidos promotores da educação para líderes cristãos hispânicos?',
        'p2' => '<b>Você encontrou o lugar:</b> a coleção digital do Centro de Recursos Justo e Catherine González, um programa da Associação para a Educação Teológica Hispânica. Aqui você encontrará uma variedade de obras não publicadas do Dr. Justo L. González, como sermões, estudos bíblicos e palestras, bem como algumas de suas obras publicadas, incluindo estudos bíblicos em espanhol. Aqui você também encontrará muitos dos escritos da Dra. Catherine G. González, uma das pioneiras na educação teológica – algumas de autoria própria e outras em colaboração com Justo. Esses últimos recursos revelam claramente como os Drs. González têm colaborado e se apoiado ao longo dos anos.',
        'p3' => 'Ao longo de sua carreira de mais de sessenta anos, os Drs. González compartilharam seus pensamentos, análises e interpretações sobre uma ampla gama de temas que o inspirarão, informarão e desafiarão: ler a Bíblia de novas maneiras, encontrar o testemunho da igreja primitiva, reformar a educação teológica e praticar a justiça. Você encontrará tudo isso e muito mais ganhando vida aqui. Então, explore, faça pesquisas direcionadas, leia pequenos trechos dos documentos, aprenda com dois dos mais importantes líderes cristãos da atualidade e volte frequentemente, pois estamos constantemente carregando novos recursos.',
        'p4' => 'O acesso ao site está disponível apenas para aqueles que assinam o Centro de Recursos Justo e Catherine González ou são Amigos do Centro. Para adquirir uma assinatura, por favor <a href="https://aeth.info/en/afiliacion" target="_blank">clique aqui</a>. Para saber mais sobre como se tornar um Amigo do Centro e nos ajudar a garantir o acesso mundial ao trabalho do Dr. González, por favor <a href="friend.php" target="_blank">clique aqui</a>.',
        'p5' => 'Abaixo, no entanto, há dois exemplos de documentos disponíveis através de nossa coleção digital. Isso deve lhe dar uma ideia do que você poderia encontrar ao se tornar um Amigo do Centro ou assinante.',
        'p6' => 'Esta primeira peça, intitulada “Los ‘Padres’ Hispanos”, é uma de três palestras que Justo González deu em 2023 em um retiro de pastores hispânicos na Califórnia. Nela, ele explora a história do impacto dos “pais” espanhóis da igreja. Leia por si mesmo. <a href="https://gonzalezcenter.s3.us-east-2.amazonaws.com/d_hisp_01394.pdf" target="_blank"><i class="fas fa-file-pdf"></i> Baixar aqui</a>. A segunda peça é uma palestra intitulada “La Señal de Jonás”, que explora a diversidade da bondade e da criação de Deus. Embora o link disponível aqui seja para a versão em espanhol, este documento também está disponível em inglês e português. <a href="https://gonzalezcenter.s3.us-east-2.amazonaws.com/d_sena_00005.pdf" target="_blank"><i class="fas fa-file-pdf"></i> Baixar aqui</a>.',
    ),
    'learn_more' => 'Saiba Mais',
    'about_desc' => array(
        'p1' => 'A Associação para a Educação Teológica Hispânica (AETH) foi fundada em 1992, no Primeiro Encontro de Líderes e Educadores da Igreja Hispânica. Desde o início, buscou reunir uma ampla gama de pessoas envolvidas nos estudos teológicos: professores e estudantes de faculdades bíblicas, institutos bíblicos e universidades de pesquisa, pastores, líderes denominacionais e outros. Um de seus principais propósitos tem sido promover o contato e a troca de ideias entre esses diferentes grupos, para o benefício da igreja e da sociedade.',
        'p2' => 'Em 2011, a AETH decidiu criar o Centro de Recursos Teológicos Justo González para atender à necessidade de recursos teológicos acessíveis, focados e relevantes para o contexto hispânico. O Centro foi posteriormente renomeado como Centro de Recursos Justo e Catherine González, em reconhecimento à significativa contribuição da Dra. Catherine Gunsalus González para a educação teológica e ao seu compromisso com o ministério da AETH. O Centro foi criado como um programa da AETH e, entre outras coisas, seria o local para abrigar a extensa coleção de escritos dos González e as recordações acumuladas ao longo de suas longas carreiras na educação teológica.',
        'p3' => 'Naquele ano, o conselho de diretores da AETH decidiu aceitar o convite do Seminário Teológico Asbury para que sua extensão em Orlando servisse como sede da AETH. Durante a década seguinte, as instalações de Asbury em Orlando foram a casa do Centro, bem como a sede da AETH, que compartilhava o mesmo corpo de funcionários. Em 2021, o Seminário Asbury decidiu vender sua propriedade em Orlando, e a AETH e o Centro González tiveram que encontrar novos lares.',
        'p4' => 'A AETH agora funciona como uma organização virtual, com sua equipe trabalhando remotamente. A única parte da organização que necessitava de um espaço físico era o Centro, com todos os seus livros, prêmios, placas e capas de doutorados honorários dados aos González. A Cooperative Baptist ofereceu espaço em sua sede em Atlanta, Geórgia. Desde 2021, o espaço do Centro no CBF tem funcionado, como diz a Dra. Jessica Lugo, Diretora Executiva da AETH, como "a presença física da AETH".',
        'p5' => 'Com o maravilhoso espaço oferecido pelo CBF, o Centro tem sido capaz de focar em sua missão central com seus objetivos e visão claramente definidos.',
    ),

);
